### ISSUE TITLE
Brightness module error

### ISSUE THREAD

**Issue by amhenikoff** [phultquist/smart-album-cover#38]
Traceback (most recent call last):
  File "run.py", line 5, in <module>
    import index
  File "/home/pi/smart-album-cover/src/index.py", line 60, in <module>
    set_brightness(get_brightness())
  File "/home/pi/smart-album-cover/src/index.py", line 42, in get_brightness
    return brightness.get_output_brightness(brightness_setting, l, max_brightness=max_brightness, min_brightness=min_brightness)
AttributeError: module 'brightness' has no attribute 'get_output_brightness'

**Comment by phultquist** [comment]
Fixed; had to reclone the repo. No issues though
